refresh = 7
version = 20160127.01

urls = ['http://www.taloussanomat.fi',
        'http://www.taloussanomat.fi/rss-syotteet/',
        'http://www.taloussanomat.fi/rss',
        'http://www.taloussanomat.fi/rss/luetuimmat',
        'http://www.taloussanomat.fi/rss/nimitykset',
        'http://www.taloussanomat.fi/rss/uudet',
        'http://www.taloussanomat.fi/rss/rating-muutokset',
        'http://www.taloussanomat.fi/rss/protestit',
        'http://www.taloussanomat.fi/rss/uutiset',
        'http://www.taloussanomat.fi/rss/uutiset/kotimaa',
        'http://www.taloussanomat.fi/rss/uutiset/ulkomaat',
        'http://www.taloussanomat.fi/rss/uutiset/ymparisto',
        'http://www.taloussanomat.fi/rss/uutiset/kansantalous',
        'http://www.taloussanomat.fi/rss/uutiset/politiikka',
        'http://www.taloussanomat.fi/rss/uutiset/kauppa',
        'http://www.taloussanomat.fi/rss/uutiset/tyomarkkinat',
        'http://www.taloussanomat.fi/rss/uutiset/palvelut',
        'http://www.taloussanomat.fi/rss/uutiset/yritykset',
        'http://www.taloussanomat.fi/rss/uutiset/ihmiset',
        'http://www.taloussanomat.fi/rss/porssi',
        'http://www.taloussanomat.fi/rss/uutiset/energia',
        'http://www.taloussanomat.fi/rss/uutiset/perusteollisuus',
        'http://www.taloussanomat.fi/rss/uutiset/teollisuustuotteet',
        'http://www.taloussanomat.fi/rss/uutiset/kulutustavarat',
        'http://www.taloussanomat.fi/rss/uutiset/paivittaistavarat',
        'http://www.taloussanomat.fi/rss/uutiset/terveydenhuolto',
        'http://www.taloussanomat.fi/rss/uutiset/rahoitus',
        'http://www.taloussanomat.fi/rss/uutiset/informaatioteknologia',
        'http://www.taloussanomat.fi/rss/uutiset/tietoliikenne',
        'http://www.taloussanomat.fi/rss/uutiset/yhdyskuntapalvelut',
        'http://www.taloussanomat.fi/rss/porssi',
        'http://www.taloussanomat.fi/rss/porssi/katsaukset',
        'http://www.itviikko.fi/uutisboksi/rssindex.xml',
        'http://www.taloussanomat.fi/rss/markkinointi',
        'http://www.taloussanomat.fi/rss/markkinointi/ihmiset',
        'http://www.taloussanomat.fi/rss/markkinointi/markkinointi',
        'http://www.taloussanomat.fi/rss/markkinointi/mainonta',
        'http://www.taloussanomat.fi/rss/markkinointi/media',
        'http://www.taloussanomat.fi/rss/markkinointi/myynti',
        'http://www.taloussanomat.fi/rss/yrittaja',
        'http://www.taloussanomat.fi/rss/yrittaja/ihmiset',
        'http://www.taloussanomat.fi/rss/yrittaja/tekniikka',
        'http://www.taloussanomat.fi/rss/asuminen',
        'http://www.taloussanomat.fi/rss/autot',
        'http://www.taloussanomat.fi/rss/tyo-ja-elama',
        'http://www.taloussanomat.fi/rss/ajatukset']
regex = [r'^http?:\/\/[^\/]*taloussanomat\.fi']
videoregex = []
liveregex = []

