refresh = 1800
version = 20160326.02

urls = ['http://o.canada.com/',
	'http://o.canada.com/category/news',
	'http://o.canada.com/category/life',
	'http://o.canada.com/category/technology',
	'http://o.canada.com/category/entertainment',
	'http://o.canada.com/category/business',
	'http://o.canada.com/category/sports',
	'http://rss.canada.com/get/?F1919', 
	'http://rss.canada.com/get/?F229', 
	'http://rss.canada.com/get/?F259', 
	'http://rss.canada.com/get/?F260', 
	'http://rss.canada.com/get/?F6956', 
	'http://rss.canada.com/get/?F6957', 
	'http://rss.canada.com/get/?F6960', 
	'http://rss.canada.com/get/?F6961', 
	'http://rss.canada.com/get/?F6962', 
	'http://rss.canada.com/get/?F6963', 
	'http://rss.canada.com/get/?F6964', 
	'http://rss.canada.com/get/?F6965', 
	'http://rss.canada.com/get/?F6966', 
	'http://rss.canada.com/get/?F6967', 
	'http://rss.canada.com/get/?F6968', 
	'http://rss.canada.com/get/?F7431', 
	'http://rss.canada.com/get/?F7432', 
	'http://rss.canada.com/get/?F7433', 
	'http://rss.canada.com/get/?F7434', 
	'http://rss.canada.com/get/?F7435', 
	'http://rss.canada.com/get/?F7436', 
	'http://rss.canada.com/get/?F7437', 
	'http://rss.canada.com/get/?F7438', 
	'http://rss.canada.com/get/?F7439', 
	'http://rss.canada.com/get/?F7440', 
	'http://rss.canada.com/get/?F7441', 
	'http://rss.canada.com/get/?F7450', 
	'http://rss.canada.com/get/?F7451', 
	'http://rss.canada.com/get/?F7452', 
	'http://rss.canada.com/get/?F7454', 
	'http://rss.canada.com/get/?F7455', 
	'http://rss.canada.com/get/?F7456', 
	'http://rss.canada.com/get/?F7457', 
	'http://rss.canada.com/get/?F7459', 
	'http://rss.canada.com/get/?F7460', 
	'http://rss.canada.com/get/?F7461', 
	'http://rss.canada.com/get/?F7462', 
	'http://rss.canada.com/get/?F7463', 
	'http://rss.canada.com/get/?F7464', 
	'http://rss.canada.com/get/?F7465', 
	'http://rss.canada.com/get/?F7466', 
	'http://rss.canada.com/get/?F7467', 
	'http://rss.canada.com/get/?F7468', 
	'http://rss.canada.com/get/?F7469', 
	'http://rss.canada.com/get/?F7470', 
	'http://rss.canada.com/get/?F7471', 
	'http://rss.canada.com/get/?F7472', 
	'http://rss.canada.com/get/?F7473', 
	'http://rss.canada.com/get/?F7474', 
	'http://rss.canada.com/get/?F7475', 
	'http://rss.canada.com/get/?F7476', 
	'http://rss.canada.com/get/?F7477', 
	'http://rss.canada.com/get/?F7478', 
	'http://rss.canada.com/get/?F7479', 
	'http://rss.canada.com/get/?F7480', 
	'http://rss.canada.com/get/?F7481', 
	'http://rss.canada.com/get/?F7482', 
	'http://rss.canada.com/get/?F7483', 
	'http://rss.canada.com/get/?F7484', 
	'http://rss.canada.com/get/?F7485', 
	'http://rss.canada.com/get/?F7486', 
	'http://rss.canada.com/get/?F7487', 
	'http://rss.canada.com/get/?F7492', 
	'http://rss.canada.com/get/?F7493', 
	'http://rss.canada.com/get/?F7939', 
	'http://rss.canada.com/get/?F8328', 
	'http://rss.canada.com/get/?F8564', 
	'http://rss.canada.com/get/?F8830']
regex = [r'^https?:\/\/[^\/]*vancouversun\.com\/']	
videoregex = [r'video']
liveregex = []


