refresh = 7200
version = 20161106.01

urls = ['http://www.iltasanomat.fi',
        'http://www.iltasanomat.fi/rss/tuoreimmat.xml',
        'http://www.iltasanomat.fi/rss/kotimaa.xml',
        'http://www.iltasanomat.fi/rss/ulkomaat.xml',
        'http://www.iltasanomat.fi/rss/urheilu.xml',
        'http://www.iltasanomat.fi/rss/jaakiekko.xml',
        'http://www.iltasanomat.fi/rss/sm-liiga.xml',
        'http://www.iltasanomat.fi/rss/nhl.xml',
        'http://www.iltasanomat.fi/rss/elitserien.xml',
        'http://www.iltasanomat.fi/rss/khl.xml',
        'http://www.iltasanomat.fi/rss/mmkiekko.xml',
        'http://www.iltasanomat.fi/rss/jalkapallo.xml',
        'http://www.iltasanomat.fi/rss/mestarienliiga.xml',
        'http://www.iltasanomat.fi/rss/veikkausliiga.xml',
        'http://www.iltasanomat.fi/rss/valioliiga.xml',
        'http://www.iltasanomat.fi/rss/allsvenskan.xml',
        'http://www.iltasanomat.fi/rss/huuhkajat.xml',
        'http://www.iltasanomat.fi/rss/hiihtolajit.xml',
        'http://www.iltasanomat.fi/rss/makihyppy.xml',
        'http://www.iltasanomat.fi/rss/maastohiihto.xml',
        'http://www.iltasanomat.fi/rss/yhdistetty.xml',
        'http://www.iltasanomat.fi/rss/ampumahiihto.xml',
        'http://www.iltasanomat.fi/rss/alppihiihto.xml',
        'http://www.iltasanomat.fi/rss/lumilautailu.xml',
        'http://www.iltasanomat.fi/rss/freestyle.xml',
        'http://www.iltasanomat.fi/rss/taitoluistelu.xml',
        'http://www.iltasanomat.fi/rss/formula1.xml',
        'http://www.iltasanomat.fi/rss/ralli.xml',
        'http://www.iltasanomat.fi/rss/moottoripyoraily.xml',
        'http://www.iltasanomat.fi/rss/yleisurheilu.xml',
        'http://www.iltasanomat.fi/rss/uinti.xml',
        'http://www.iltasanomat.fi/rss/koripallo.xml',
        'http://www.iltasanomat.fi/rss/lentopallo.xml',
        'http://www.iltasanomat.fi/rss/salibandy.xml',
        'http://www.iltasanomat.fi/rss/tennis.xml',
        'http://www.iltasanomat.fi/rss/pesapallo.xml',
        'http://www.iltasanomat.fi/rss/purjehdus.xml',
        'http://www.iltasanomat.fi/rss/nyrkkeily.xml',
        'http://www.iltasanomat.fi/rss/golf.xml',
        'http://www.iltasanomat.fi/rss/ravit.xml',
        'http://www.iltasanomat.fi/rss/viihde.xml',
        'http://www.iltasanomat.fi/rss/elokuvat.xml',
        'http://www.iltasanomat.fi/rss/kuninkaalliset.xml',
        'http://www.iltasanomat.fi/rss/bigbrother.xml',
        'http://www.iltasanomat.fi/rss/miss-suomi.xml',
        'http://www.iltasanomat.fi/rss/linnanjuhlat.xml',
        'http://www.iltasanomat.fi/rss/euroviisut.xml',
        'http://www.iltasanomat.fi/rss/idols.xml',
        'http://www.iltasanomat.fi/rss/tanssiitahtienkanssa.xml',
        'http://www.iltasanomat.fi/rss/diili.xml',
        'http://www.iltasanomat.fi/rss/hyvaolo.xml',
        'http://www.iltasanomat.fi/rss/muotikauneus.xml',
        'http://www.iltasanomat.fi/rss/autot.xml',
        'http://www.iltasanomat.fi/rss/matkat.xml',
        'http://www.iltasanomat.fi/rss/asuminen.xml',
        'http://www.ruokala.net/uutiset/rss',
        'http://www.ruokala.net/ajankohtaista/rss',
        'http://www.ruokala.net/reseptit/rss',
        'http://www.iltasanomat.fi/rss/lemmikit.xml']
regex = [r'^http?:\/\/[^\/]*www.iltasanomat\.fi']
videoregex = []
liveregex = []

