refresh = 7
version = 20160326.02

urls = ['http://www.nrk.no/',
	'http://www.nrk.no/nyheter/',
	'http://www.nrk.no/sport/',
	'https://radio.nrk.no/',
	'http://www.nrk.no/norge/',
	'http://www.nrk.no/urix/',
	'http://www.nrk.no/kultur/',
	'http://www.nrk.no/livsstil/',
	'http://www.nrk.no/viten/',
	'http://www.nrk.no/dokumentar/',
	'http://www.nrk.no/ytring/',
	'http://www.nrk.no/sapmi/',
	'http://www.nrk.no/kultur/toppsaker.rss',
	'http://www.nrk.no/livsstil/toppsaker.rss',
	'http://www.nrk.no/viten/toppsaker.rss',
	'http://nrk.no/fordypning/toppsaker.rss',
	'http://nrk.no/ytring/toppsaker.rss',
	'http://www.nrk.no/sapmi/norsk.rss',
	'http://www.nrk.no/sapmi/oanehaccat.rss',
	'http://www.nrk.no/sport/fotball/toppsaker.rss',
	'http://www.nrk.no/kultur/litteratur/toppsaker.rss',
	'http://www.nrk.no/mat/aktuelt.rss',
	'http://www.nrk.no/ytring/toppsaker.rss',
	'http://www.nrk.no/ostlandssendingen/siste.rss',
	'http://www.nrk.no/ostfold/siste.rss',
	'http://www.nrk.no/ostafjells/ostafjells.rss',
	'http://www.nrk.no/ostafjells/vestfold/siste.rss',
	'http://www.nrk.no/trondelag/siste.rss',
	'http://www.nrk.no/troms/siste.rss',
	'http://www.nrk.no/ostafjells/telemark/siste.rss',
	'http://www.nrk.no/sorlandet/siste.rss',
	'http://www.nrk.no/sognogfjordane/siste.rss',
	'http://www.nrk.no/rogaland/siste.rss',
	'http://www.nrk.no/nordland/siste.rss',
	'http://www.nrk.no/mr/siste.rss',
	'http://www.nrk.no/hordaland/siste.rss',
	'http://www.nrk.no/ho/siste.rss',
	'http://www.nrk.no/finnmark/siste.rss',
	'http://www.nrk.no/ostafjells/buskerud/siste.rss',
	'http://www.nrk.no/nyheter/siste.rss',
	'http://www.nrk.no/sport/siste.rss',
	'http://www.nrk.no/norge/toppsaker.rss',
	'http://www.nrk.no/urix/toppsaker.rss',
	'http://www.nrk.no/sport/toppsaker.rss',
	'http://www.nrk.no/ostafjells/buskerud/toppsaker.rss',
	'http://www.nrk.no/finnmark/toppsaker.rss',
	'http://www.nrk.no/ho/toppsaker.rss',
	'http://www.nrk.no/hordaland/toppsaker.rss',
	'http://www.nrk.no/mr/toppsaker.rss',
	'http://www.nrk.no/nordland/toppsaker.rss',
	'http://www.nrk.no/rogaland/toppsaker.rss',
	'http://www.nrk.no/sognogfjordane/toppsaker.rss',
	'http://www.nrk.no/sorlandet/toppsaker.rss',
	'http://www.nrk.no/ostafjells/telemark/toppsaker.rss',
	'http://www.nrk.no/troms/toppsaker.rss',
	'http://www.nrk.no/trondelag/toppsaker.rss',
	'http://www.nrk.no/ostafjells/vestfold/toppsaker.rss',
	'http://www.nrk.no/ostafjells/toppsaker.rss',
	'http://www.nrk.no/ostfold/toppsaker.rss',
	'http://www.nrk.no/ostlandssendingen/toppsaker.rss']
regex = [r'https?:\/\/[^\/]*nrk\.no']
videoregex = []
liveregex = []
