refresh = 21600
version = 20160402.01

urls = ['http://thump.vice.com/',
	'http://thump.vice.com/en_us',
	'http://thump.vice.com/en_us/videos',
	'http://thump.vice.com/en_us/tracks',
	'http://thump.vice.com/en_us/articles',
	'http://thump.vice.com/en_us/topic/thump-presents',
	'http://thump.vice.com/en_us/rss',
	'http://thump.vice.com/en_au',
	'http://thump.vice.com/en_au/videos',
	'http://thump.vice.com/en_au/tracks',
	'http://thump.vice.com/en_au/articles',
	'http://thump.vice.com/en_au/topic/thump-presents',
	'http://thump.vice.com/en_au/rss',
	'http://thump.vice.com/pt_br',
	'http://thump.vice.com/pt_br/videos',
	'http://thump.vice.com/pt_br/tracks',
	'http://thump.vice.com/pt_br/articles',
	'http://thump.vice.com/pt_br/topic/thump-presents',
	'http://thump.vice.com/pt_br/rss',
	'http://thump.vice.com/en_ca',
	'http://thump.vice.com/en_ca/videos',
	'http://thump.vice.com/en_ca/tracks',
	'http://thump.vice.com/en_ca/articles',
	'http://thump.vice.com/en_ca/topic/thump-presents',
	'http://thump.vice.com/en_ca/rss',
	'http://thump.vice.com/de',
	'http://thump.vice.com/de/videos',
	'http://thump.vice.com/de/tracks',
	'http://thump.vice.com/de/articles',
	'http://thump.vice.com/de/topic/thump-presents',
	'http://thump.vice.com/de/rss',
	'http://thump.vice.com/es_mx',
	'http://thump.vice.com/es_mx/videos',
	'http://thump.vice.com/es_mx/tracks',
	'http://thump.vice.com/es_mx/articles',
	'http://thump.vice.com/es_mx/topic/thump-presents',
	'http://thump.vice.com/es_mx/rss',
	'http://thump.vice.com/en_us',
	'http://thump.vice.com/nl/videos',
	'http://thump.vice.com/nl/tracks',
	'http://thump.vice.com/nl/articles',
	'http://thump.vice.com/nl/topic/thump-presents',
	'http://thump.vice.com/nl/rss',
	'http://thump.vice.com/en_us',
	'http://thump.vice.com/en_uk/videos',
	'http://thump.vice.com/en_uk/tracks',
	'http://thump.vice.com/en_uk/articles',
	'http://thump.vice.com/en_uk/topic/thump-presents',
	'http://thump.vice.com/en_uk/rss',
	'http://thump.vice.com/en_us',
	'http://thump.vice.com/es_co/videos',
	'http://thump.vice.com/es_co/tracks',
	'http://thump.vice.com/es_co/articles',
	'http://thump.vice.com/es_co/topic/thump-presents',
	'http://thump.vice.com/es_co/rss']
regex = [r'^https?:\/\/[^\/]*thump\.vice\.com']
videoregex = ['\/video\/', '\/show\/']
liveregex = []