refresh = 2
version = 20151221.01

urls = ['http://www.cbc.ca',
        'http://rss.cbc.ca/lineup/world.xml',
        'http://rss.cbc.ca/lineup/canada.xml',
        'http://rss.cbc.ca/lineup/politics.xml',
        'http://rss.cbc.ca/lineup/business.xml',
        'http://rss.cbc.ca/lineup/health.xml',
        'http://rss.cbc.ca/lineup/arts.xml',
        'http://rss.cbc.ca/lineup/technology.xml',
        'http://rss.cbc.ca/lineup/offbeat.xml',
        'http://www.cbc.ca/cmlink/rss-cbcaboriginal',
        'http://rss.cbc.ca/lineup/sports.xml',
        'http://rss.cbc.ca/lineup/sports-mlb.xml',
        'http://rss.cbc.ca/lineup/sports-nba.xml',
        'http://rss.cbc.ca/lineup/sports-curling.xml',
        'http://rss.cbc.ca/lineup/sports-cfl.xml',
        'http://rss.cbc.ca/lineup/sports-nfl.xml',
        'http://rss.cbc.ca/lineup/sports-nhl.xml',
        'http://rss.cbc.ca/lineup/sports-soccer.xml',
        'http://rss.cbc.ca/lineup/sports-figureskating.xml',
        'http://rss.cbc.ca/lineup/canada-britishcolumbia.xml',
        'http://rss.cbc.ca/lineup/canada-kamloops.xml',
        'http://rss.cbc.ca/lineup/canada-calgary.xml',
        'http://rss.cbc.ca/lineup/canada-edmonton.xml',
        'http://rss.cbc.ca/lineup/canada-saskatchewan.xml',
        'http://rss.cbc.ca/lineup/canada-saskatoon.xml',
        'http://rss.cbc.ca/lineup/canada-manitoba.xml',
        'http://rss.cbc.ca/lineup/canada-thunderbay.xml',
        'http://rss.cbc.ca/lineup/canada-sudbury.xml',
        'http://rss.cbc.ca/lineup/canada-windsor.xml',
        'http://rss.cbc.ca/lineup/canada-kitchenerwaterloo.xml',
        'http://rss.cbc.ca/lineup/canada-toronto.xml',
        'http://rss.cbc.ca/lineup/canada-ottawa.xml',
        'http://rss.cbc.ca/lineup/canada-montreal.xml',
        'http://rss.cbc.ca/lineup/canada-newbrunswick.xml',
        'http://rss.cbc.ca/lineup/canada-pei.xml',
        'http://rss.cbc.ca/lineup/canada-novascotia.xml',
        'http://rss.cbc.ca/lineup/canada-newfoundland.xml',
        'http://rss.cbc.ca/lineup/canada-north.xml',
        'http://rss.cbc.ca/lineup/canada-hamiltonnews.xml',
        'http://rss.cbc.ca/lineup/canada-hamiltoncommute.xml',
        'http://rss.cbc.ca/lineup/canada-hamiltoneconomy.xml',
        'http://rss.cbc.ca/lineup/canada-hamiltontalk.xml',
        'http://rss.cbc.ca/lineup/canada-hamiltonthingstodo.xml',
        'http://rss.cbc.ca/lineup/thenational.xml',
        'http://www.cbc.ca/contact/blog/index.xml',
        'http://www.cbc.ca/cmlink/rss-quirks',
        'http://www.cbc.ca/cmlink/rss-the180',
        'http://www.cbc.ca/cmlink/rss-asithappens',
        'http://www.cbc.ca/cmlink/rss-cestlavie',
        'http://www.cbc.ca/cmlink/rss-checkup',
        'http://www.cbc.ca/cmlink/rss-thecurrent',
        'http://www.cbc.ca/cmlink/rss-DNTO',
        'http://www.cbc.ca/cmlink/rss-day6',
        'http://www.cbc.ca/cmlink/rss-debaters',
        'http://www.cbc.ca/cmlink/rss-thehouse',
        'http://www.cbc.ca/cmlink/rss-ideas',
        'http://www.cbc.ca/cmlink/rss-inthefield',
        'http://www.cbc.ca/cmlink/rss-laughoutloud',
        'http://www.cbc.ca/cmlink/rss-thenextchapter',
        'http://www.cbc.ca/cmlink/rss-q',
        'http://www.cbc.ca/cmlink/rss-rewind',
        'http://www.cbc.ca/cmlink/rss-spark',
        'http://www.cbc.ca/cmlink/rss-storyfromhere',
        'http://www.cbc.ca/cmlink/rss-sundayedition',
        'http://www.cbc.ca/cmlink/rss-tapestry',
        'http://www.cbc.ca/cmlink/rss-thisisthat',
        'http://www.cbc.ca/cmlink/rss-undertheinfluence',
        'http://www.cbc.ca/cmlink/rss-whitecoat',
        'http://www.cbc.ca/cmlink/rss-wiretap',
        'http://www.cbc.ca/cmlink/rss-writersandco',
        'http://www.cbc.ca/nl/blogs/seen/atom.xml',
        'http://www.cbc.ca/nl/features/nlweather/index.xml',
        'http://www.cbc.ca/informationmorningcb/atom.xml',
        'http://www.cbc.ca/morningedition/index.xml',
        'http://www.cbc.ca/metromorning/index.xml',
        'http://www.cbc.ca/maritimenoon/atom.xml',
        'http://www.cbc.ca/landandsea/atom.xml',
        'http://www.cbc.ca/littlemosque/blog/index.xml',
        'http://www.cbc.ca/thenational/blog/atom.xml']
regex = [r'^https?:\/\/[^\/]*cbc\.ca\/']	
videoregex = [r'/player/play/',
        r'/videos/',
        r'/episodes/',
        r'/player/play/',
        r'/player/play/',
        r'/player/play/']
liveregex = []


