refresh = 7
version = 20160124.01

urls = ['http://blogs.wsj.com/bankruptcy/feed/',
	'http://blogs.wsj.com/capitaljournal/feed/',
	'http://blogs.wsj.com/chinarealtime/feed/',
	'http://blogs.wsj.com/corruption-currents/feed/',
	'http://feeds.wsjonline.com/wsj/dailyfix/feed/',
	'http://feeds.wsjonline.com/wsj/deals/feed',
	'http://feeds.wsjonline.com/wsj/developments/feed',
	'http://feeds.wsjonline.com/wsj/biztech/feed',
	'http://blogs.wsj.com/dispatch/feed/',
	'http://blogs.wsj.com/drivers-seat/feed/',
	'http://blogs.wsj.com/exchange/feed/',
	'http://blogs.wsj.com/financial-adviser/feed/',
	'http://blogs.wsj.com/management/feed/',
	'http://blogs.wsj.com/health/feed/',
	'http://blogs.wsj.com/runway/feed/',
	'http://blogs.wsj.com/hire-education/feed/',
	'http://blogs.wsj.com/hong-kong/feed/',
	'http://blogs.wsj.com/ideas-market/feed/',
	'http://blogs.wsj.com/indiarealtime/feed/',
	'http://blogs.wsj.com/japanrealtime/feed/',
	'http://blogs.wsj.com/juggle/feed/',
	'http://blogs.wsj.com/korearealtime/feed/',
	'http://blogs.wsj.com/law/feed/',
	'http://blogs.wsj.com/marketbeat/feed/',
	'http://blogs.wsj.com/metropolis/feed/',
	'http://blogs.wsj.com/middleseat/feed/',
	'http://mobilefeeds.wsj.com/xml/feed/v2/3_8461.rss',
	'http://blogs.wsj.com/emergingeurope/feed/',
	'http://feeds.wsjonline.com/wsj/numbersguy/feed',
	'http://blogs.wsj.com/wine/feed/',
	'http://blogs.wsj.com/photojournal/feed/',
	'http://blogs.wsj.com/privateequity/feed/',
	'http://blogs.wsj.com/brussels/feed/',
	'http://feeds.wsjonline.com/wsj/economics/feed',
	'http://blogs.wsj.com/scene/feed/',
	'http://blogs.wsj.com/simonnixon/feed/',
	'http://feeds2.feedburner.com/wsj/speakeasy/feed/',
	'http://blogs.wsj.com/venturecapital/feed/',
	'http://blogs.wsj.com/washwire/feed/',
	'http://blogs.wsj.com/wealth/feed/',
	'http://blogs.wsj.com/puzzle/feed/']
regex = [r'^https?:\/\/[^\/]*wsj\.com', r'^https?:\/\/[^\/]*wsj\.net', r'^https?:\/\/[^\/]*wsjonline\.com', r'^https?:\/\/[^\/]*feedburner\.com']
videoregex = [r'video']
liveregex = [r'live']