refresh = 1800
version = 20160326.02

urls = ['http://am.radiovaticana.va/',
	'http://am.radiovaticana.va/',
	'http://ar.radiovaticana.va/',
	'http://be.radiovaticana.va/',
	'http://bg.radiovaticana.va/',
	'http://br.radiovaticana.va/',
	'http://cs.radiovaticana.va/',
	'http://de.radiovaticana.va/',
	'http://en.radiovaticana.va/',
	'http://eo.radiovaticana.va/',
	'http://es.radiovaticana.va/',
	'http://fi.radiovaticana.va/',
	'http://fr.radiovaticana.va/',
	'http://he.radiovaticana.va/',
	'http://hi.radiovaticana.va/',
	'http://hr.radiovaticana.va/',
	'http://hu.radiovaticana.va/',
	'http://hy.radiovaticana.va/',
	'http://ja.radiovaticana.va/',
	'http://kr.radiovaticana.va/',
	'http://lt.radiovaticana.va/',
	'http://lv.radiovaticana.va/',
	'http://mk.radiovaticana.va/',
	'http://ml.radiovaticana.va/',
	'http://pl.radiovaticana.va/',
	'http://pt.radiovaticana.va/',
	'http://ro.radiovaticana.va/',
	'http://ru.radiovaticana.va/',
	'http://sk.radiovaticana.va/',
	'http://sl.radiovaticana.va/',
	'http://sq.radiovaticana.va/',
	'http://sv.radiovaticana.va/',
	'http://sw.radiovaticana.va/',
	'http://ta.radiovaticana.va/',
	'http://ti.radiovaticana.va/',
	'http://uk.radiovaticana.va/',
	'http://vi.radiovaticana.va/',
	'http://zh.radiovaticana.va/',
	'http://am.radiovaticana.va/feed/rss-articoli-standard',
	'http://ar.radiovaticana.va/feed/rss-articoli-standard',
	'http://be.radiovaticana.va/feed/rss-articoli-standard',
	'http://bg.radiovaticana.va/feed/rss-articoli-standard',
	'http://br.radiovaticana.va/feed/rss-articoli-standard',
	'http://cs.radiovaticana.va/feed/rss-articoli-standard',
	'http://de.radiovaticana.va/feed/rss-articoli-standard',
	'http://en.radiovaticana.va/feed/rss-articoli-standard',
	'http://eo.radiovaticana.va/feed/rss-articoli-standard',
	'http://es.radiovaticana.va/feed/rss-articoli-standard',
	'http://fi.radiovaticana.va/feed/rss-articoli-standard',
	'http://fr.radiovaticana.va/feed/rss-articoli-standard',
	'http://he.radiovaticana.va/feed/rss-articoli-standard',
	'http://hi.radiovaticana.va/feed/rss-articoli-standard',
	'http://hr.radiovaticana.va/feed/rss-articoli-standard',
	'http://hu.radiovaticana.va/feed/rss-articoli-standard',
	'http://hy.radiovaticana.va/feed/rss-articoli-standard',
	'http://ja.radiovaticana.va/feed/rss-articoli-standard',
	'http://kr.radiovaticana.va/feed/rss-articoli-standard',
	'http://lt.radiovaticana.va/feed/rss-articoli-standard',
	'http://lv.radiovaticana.va/feed/rss-articoli-standard',
	'http://mk.radiovaticana.va/feed/rss-articoli-standard',
	'http://ml.radiovaticana.va/feed/rss-articoli-standard',
	'http://pl.radiovaticana.va/feed/rss-articoli-standard',
	'http://pt.radiovaticana.va/feed/rss-articoli-standard',
	'http://ro.radiovaticana.va/feed/rss-articoli-standard',
	'http://ru.radiovaticana.va/feed/rss-articoli-standard',
	'http://sk.radiovaticana.va/feed/rss-articoli-standard',
	'http://sl.radiovaticana.va/feed/rss-articoli-standard',
	'http://sq.radiovaticana.va/feed/rss-articoli-standard',
	'http://sv.radiovaticana.va/feed/rss-articoli-standard',
	'http://sw.radiovaticana.va/feed/rss-articoli-standard',
	'http://ta.radiovaticana.va/feed/rss-articoli-standard',
	'http://ti.radiovaticana.va/feed/rss-articoli-standard',
	'http://uk.radiovaticana.va/feed/rss-articoli-standard',
	'http://vi.radiovaticana.va/feed/rss-articoli-standard',
	'http://zh.radiovaticana.va/feed/rss-articoli-standard']
regex = [r'^https?:\/\/[^\/]*radiovaticana\.va\/']	
videoregex = [r'video']
liveregex = []


