refresh = 1800
version = 20160326.02

urls = ['http://www.pajhwok.com/',
	'http://www.pajhwok.com/en/governance-politics',
	'http://www.pajhwok.com/en/security-crime',
	'http://www.pajhwok.com/en/business-economics',
	'http://www.pajhwok.com/en/education',
	'http://www.pajhwok.com/en/health',
	'http://www.pajhwok.com/en/agriculture',
	'http://www.pajhwok.com/en/reconstruction',
	'http://www.pajhwok.com/en/migration',
	'http://www.pajhwok.com/en/accidents-disasters',
	'http://www.pajhwok.com/en/religion-culture',
	'http://www.pajhwok.com/en/society',
	'http://www.pajhwok.com/en/women',
	'http://www.pajhwok.com/en/innovation-technology',
	'http://www.pajhwok.com/en/environment',
	'http://www.pajhwok.com/en/sports',
	'http://www.pajhwok.com/dr/governance-politics',
	'http://www.pajhwok.com/dr/security-crime',
	'http://www.pajhwok.com/dr/business-economics',
	'http://www.pajhwok.com/dr/education',
	'http://www.pajhwok.com/dr/health',
	'http://www.pajhwok.com/dr/agriculture',
	'http://www.pajhwok.com/dr/reconstruction',
	'http://www.pajhwok.com/dr/migration',
	'http://www.pajhwok.com/dr/accidents-disasters',
	'http://www.pajhwok.com/dr/religion-culture',
	'http://www.pajhwok.com/dr/society',
	'http://www.pajhwok.com/dr/women',
	'http://www.pajhwok.com/dr/innovation-technology',
	'http://www.pajhwok.com/dr/environment',
	'http://www.pajhwok.com/dr/sports',	
	'http://www.pajhwok.com/ps/governance-politics',
	'http://www.pajhwok.com/ps/security-crime',
	'http://www.pajhwok.com/ps/business-economics',
	'http://www.pajhwok.com/ps/education',
	'http://www.pajhwok.com/ps/health',
	'http://www.pajhwok.com/ps/agriculture',
	'http://www.pajhwok.com/ps/reconstruction',
	'http://www.pajhwok.com/ps/migration',
	'http://www.pajhwok.com/ps/accidents-disasters',
	'http://www.pajhwok.com/ps/religion-culture',
	'http://www.pajhwok.com/ps/society',
	'http://www.pajhwok.com/ps/women',
	'http://www.pajhwok.com/ps/innovation-technology',
	'http://www.pajhwok.com/ps/environment',
	'http://www.pajhwok.com/ps/sports',
	'http://www.pajhwok.com/en/nodequeue/1/feed',
	'http://www.pajhwok.com/en/nodequeue/2/feed',
	'http://www.pajhwok.com/en/nodequeue/3/feed',
	'http://www.pajhwok.com/dr/nodequeue/1/feed',
	'http://www.pajhwok.com/dr/nodequeue/2/feed',
	'http://www.pajhwok.com/dr/nodequeue/3/feed',
	'http://www.pajhwok.com/ps/nodequeue/1/feed',
	'http://www.pajhwok.com/ps/nodequeue/2/feed',
	'http://www.pajhwok.com/ps/nodequeue/3/feed']
regex = [r'^https?:\/\/[^\/]*pajhwok\.com']
videoregex = []
liveregex = []


