refresh = 8
version = 20160402.01

urls = ['http://i-d.vice.com',
	'http://i-d.vice.com/nl',
	'http://i-d.vice.com/nl/videos',
	'http://i-d.vice.com/nl/topic/mode',
	'http://i-d.vice.com/nl/topic/muziek',
	'http://i-d.vice.com/nl/topic/cultuur',
	'http://i-d.vice.com/nl/topic/think-pieces',
	'http://i-d.vice.com/nl/rss',
	'http://i-d.vice.com/en_gb',
	'http://i-d.vice.com/en_gb/topic/fashion',
	'http://i-d.vice.com/en_gb/topic/music',
	'http://i-d.vice.com/en_gb/topic/news',
	'http://i-d.vice.com/en_gb/topic/think-pieces',
	'http://i-d.vice.com/en_gb/rss',
	'http://i-d.vice.com/de_de',
	'http://i-d.vice.com/de_de/videos',
	'http://i-d.vice.com/de_de/topic/fashion',
	'http://i-d.vice.com/de_de/topic/musik',
	'http://i-d.vice.com/de_de/topic/kultur',
	'http://i-d.vice.com/de_de/topic/news',
	'http://i-d.vice.com/de_de/topic/meinung',
	'http://i-d.vice.com/de_de/rss',
	'http://i-d.vice.com/it',
	'http://i-d.vice.com/it/topic/moda',
	'http://i-d.vice.com/it/topic/musica',
	'http://i-d.vice.com/it/topic/news',
	'http://i-d.vice.com/it/topic/opinioni',
	'http://i-d.vice.com/it/rss',
	'http://i-d.vice.com/es_mx',
	'http://i-d.vice.com/es_mx/videos',
	'http://i-d.vice.com/es_mx/topic/moda',
	'http://i-d.vice.com/es_mx/topic/m%C3%BAsica',
	'http://i-d.vice.com/es_mx/topic/cultura',
	'http://i-d.vice.com/es_mx/topic/noticias',
	'http://i-d.vice.com/es_mx/topic/think-pieces',
	'http://i-d.vice.com/es_mx/rss',
	'http://i-d.vice.com/pl',
	'http://i-d.vice.com/pl/videos',
	'http://i-d.vice.com/pl/topic/Moda',
	'http://i-d.vice.com/pl/topic/Muzyka',
	'http://i-d.vice.com/pl/topic/Kultura',
	'http://i-d.vice.com/pl/topic/newsy',
	'http://i-d.vice.com/pl/topic/opinie',
	'http://i-d.vice.com/pl/rss',
	'http://i-d.vice.com/en_au',
	'http://i-d.vice.com/en_au/topic/fashion',
	'http://i-d.vice.com/en_au/topic/music',
	'http://i-d.vice.com/en_au/topic/culture',
	'http://i-d.vice.com/en_au/rss',
	'http://i-d.vice.com/en_us',
	'http://i-d.vice.com/en_us/topic/fashion',
	'http://i-d.vice.com/en_us/videos',
	'http://i-d.vice.com/en_us/topic/news',
	'http://i-d.vice.com/en_us/topic/think-pieces',
	'http://i-d.vice.com/en_us/rss',
	'http://i-d.vice.com/fr',
	'http://i-d.vice.com/fr/topic/mode',
	'http://i-d.vice.com/fr/videos',
	'http://i-d.vice.com/fr/topic/culture',
	'http://i-d.vice.com/fr/topic/musique',
	'http://i-d.vice.com/fr/topic/news',
	'http://i-d.vice.com/fr/topic/opinions',
	'http://i-d.vice.com/fr/rss']
regex = [r'^https?:\/\/[^\/]*i-d\.vice\.com']
videoregex = []
liveregex = []