refresh = 7200
version = 20161106.01

urls = ['http://www.kaleva.fi/',
        'http://feeds.kauppalehti.fi/rss/main',
        'http://feeds.kauppalehti.fi/rss/popular',
        'http://feeds.kauppalehti.fi/rss/klnyt',
        'http://feeds.kauppalehti.fi/rss/topic/aasian-taloudet',
        'http://feeds.kauppalehti.fi/rss/topic/asuminen',
        'http://feeds.kauppalehti.fi/rss/topic/asuntosijoittaminen',
        'http://feeds.kauppalehti.fi/rss/topic/auto',
        'http://feeds.kauppalehti.fi/rss/topic/digitalous',
        'http://feeds.kauppalehti.fi/rss/topic/eu',
        'http://feeds.kauppalehti.fi/rss/topic/elektroniikka',
        'http://feeds.kauppalehti.fi/rss/topic/elintarvikkeet',
        'http://feeds.kauppalehti.fi/rss/topic/energia',
        'http://feeds.kauppalehti.fi/rss/topic/finanssiala',
        'http://feeds.kauppalehti.fi/rss/topic/innovaatiot',
        'http://feeds.kauppalehti.fi/rss/topic/investoinnit',
        'http://feeds.kauppalehti.fi/rss/topic/johdannaiset',
        'http://feeds.kauppalehti.fi/rss/topic/johtaminen',
        'http://feeds.kauppalehti.fi/rss/topic/kaivokset',
        'http://feeds.kauppalehti.fi/rss/topic/kansantalous',
        'http://feeds.kauppalehti.fi/rss/topic/kauppa',
        'http://feeds.kauppalehti.fi/rss/topic/kehittyvat-taloudet',
        'http://feeds.kauppalehti.fi/rss/topic/kemia',
        'http://feeds.kauppalehti.fi/rss/topic/konepajat',
        'http://feeds.kauppalehti.fi/rss/topic/konkurssit',
        'http://feeds.kauppalehti.fi/rss/topic/korot',
        'http://feeds.kauppalehti.fi/rss/topic/koulutus',
        'http://feeds.kauppalehti.fi/rss/topic/kunnat',
        'http://feeds.kauppalehti.fi/rss/topic/lifestyle',
        'http://feeds.kauppalehti.fi/rss/topic/logistiikka',
        'http://feeds.kauppalehti.fi/rss/topic/laakkeet',
        'http://feeds.kauppalehti.fi/rss/topic/markkinointi',
        'http://feeds.kauppalehti.fi/rss/topic/media',
        'http://feeds.kauppalehti.fi/rss/topic/metalli',
        'http://feeds.kauppalehti.fi/rss/topic/metsa',
        'http://feeds.kauppalehti.fi/rss/topic/metsanomistus',
        'http://feeds.kauppalehti.fi/rss/topic/nimitykset',
        'http://feeds.kauppalehti.fi/rss/topic/osakkeet',
        'http://feeds.kauppalehti.fi/rss/topic/pankit',
        'http://feeds.kauppalehti.fi/rss/topic/politiikka',
        'http://feeds.kauppalehti.fi/rss/topic/paaomasijoittaminen',
        'http://feeds.kauppalehti.fi/rss/topic/raaka-aineet',
        'http://feeds.kauppalehti.fi/rss/topic/rahastot',
        'http://feeds.kauppalehti.fi/rss/topic/rahoitus',
        'http://feeds.kauppalehti.fi/rss/topic/rakentaminen',
        'http://feeds.kauppalehti.fi/rss/topic/ravintolat',
        'http://feeds.kauppalehti.fi/rss/topic/sijoittaminen',
        'http://feeds.kauppalehti.fi/rss/topic/sote',
        'http://feeds.kauppalehti.fi/rss/topic/startup',
        'http://feeds.kauppalehti.fi/rss/topic/suhdanteet',
        'http://feeds.kauppalehti.fi/rss/topic/teollisuus',
        'http://feeds.kauppalehti.fi/rss/topic/the-financial-times',
        'http://feeds.kauppalehti.fi/rss/topic/toimitilat',
        'http://feeds.kauppalehti.fi/rss/topic/tulokset',
        'http://feeds.kauppalehti.fi/rss/topic/tutkimus',
        'http://feeds.kauppalehti.fi/rss/topic/tyoelama',
        'http://feeds.kauppalehti.fi/rss/topic/tyomarkkinat',
        'http://feeds.kauppalehti.fi/rss/topic/tyoviihtyvyys',
        'http://feeds.kauppalehti.fi/rss/topic/usa',
        'http://feeds.kauppalehti.fi/rss/topic/ura',
        'http://feeds.kauppalehti.fi/rss/topic/vaalit',
        'http://feeds.kauppalehti.fi/rss/topic/vakuutukset',
        'http://feeds.kauppalehti.fi/rss/topic/valtiontalous',
        'http://feeds.kauppalehti.fi/rss/topic/valtionyhtiot',
        'http://feeds.kauppalehti.fi/rss/topic/valuutat',
        'http://feeds.kauppalehti.fi/rss/topic/varainhoito',
        'http://feeds.kauppalehti.fi/rss/topic/velkakriisi',
        'http://feeds.kauppalehti.fi/rss/topic/venaja',
        'http://feeds.kauppalehti.fi/rss/topic/verotus',
        'http://feeds.kauppalehti.fi/rss/topic/viini',
        'http://feeds.kauppalehti.fi/rss/topic/yt-neuvottelut',
        'http://feeds.kauppalehti.fi/rss/topic/ymparisto',
        'http://feeds.kauppalehti.fi/rss/topic/yrittaminen',
        'http://feeds.kauppalehti.fi/rss/topic/yritys',
        'http://feeds.kauppalehti.fi/rss/topic/yrityskaupat',
        'http://feeds.kauppalehti.fi/rss/topic/yrityspalvelut']
regex = [r'^http?:\/\/[^\/]*kauppalehti\.fi']
videoregex = []
liveregex = []

