refresh = 7
version = 20160121.01

urls = ['http://www.elwatan.com/',
	'http://www.elwatan.com/actualite/rss.xml',
	'http://www.elwatan.com/sports/rss.xml',
	'http://www.elwatan.com/economie/rss.xml',
	'http://www.elwatan.com/international/rss.xml',
	'http://www.elwatan.com/culture/rss.xml',
	'http://www.elwatan.com/contributions/rss.xml',
	'http://www.elwatan.com/regions/est/constantine/rss.xml',
	'http://www.elwatan.com/regions/est/setif/rss.xml',
	'http://www.elwatan.com/regions/est/skikda/rss.xml',
	'http://www.elwatan.com/regions/est/jijel/rss.xml',
	'http://www.elwatan.com/regions/est/biskra/rss.xml',
	'http://www.elwatan.com/regions/est/batna/rss.xml',
	'http://www.elwatan.com/regions/est/annaba/rss.xml',
	'http://www.elwatan.com/regions/ouest/oran/rss.xml',
	'http://www.elwatan.com/regions/ouest/tiaret/rss.xml',
	'http://www.elwatan.com/regions/ouest/chlef/rss.xml',
	'http://www.elwatan.com/regions/ouest/belabes/rss.xml',
	'http://www.elwatan.com/regions/ouest/tlemcen/rss.xml',
	'http://www.elwatan.com/regions/ouest/mascara/rss.xml',
	'http://www.elwatan.com/regions/ouest/mostagenem/rss.xml',
	'http://www.elwatan.com/regions/kabylie/tiziouzou/rss.xml',
	'http://www.elwatan.com/regions/kabylie/bajaia/rss.xml',
	'http://www.elwatan.com/regions/kabylie/bouira/rss.xml',
	'http://www.elwatan.com/regions/kabylie/boumerdes/rss.xml',
	'http://www.elwatan.com/regions/centre/alger/rss.xml',
	'http://www.elwatan.com/regions/centre/tipaza/rss.xml',
	'http://www.elwatan.com/regions/centre/blida/rss.xml',
	'http://www.elwatan.com/regions/actu-regions/rss.xml',
	'http://www.elwatan.com/regions/centre/actu-centre/rss.xml',
	'http://www.elwatan.com/regions/centre/actu-est/rss.xml',
	'http://www.elwatan.com/regions/centre/actu-ouest/rss.xml',
	'http://www.elwatan.com/regions/kabylie/actu-kabylie/rss.xml',
	'http://www.elwatan.com/regions/sud/tamanrasset/rss.xml',
	'http://www.elwatan.com/regions/sud/ouargla/rss.xml',
	'http://www.elwatan.com/regions/ouest/actu-sud/rss.xml',
	'http://www.elwatan.com/hebdo/arts-et-lettres/rss.xml',
	'http://www.elwatan.com/hebdo/auto/rss.xml',
	'http://www.elwatan.com/hebdo/environnement/rss.xml',
	'http://www.elwatan.com/hebdo/france/rss.xml',
	'http://www.elwatan.com/hebdo/histoire/rss.xml',
	'http://www.elwatan.com/hebdo/mode/rss.xml',
	'http://www.elwatan.com/hebdo/multimedia/rss.xml',
	'http://www.elwatan.com/hebdo/portrait/rss.xml',
	'http://www.elwatan.com/hebdo/sante/rss.xml',
	'http://www.elwatan.com/chroniques/analyseeco/rss.xml',
	'http://www.elwatan.com/chroniques/pointzero/rss.xml',
	'http://www.elwatan.com/chroniques/repereseco/rss.xml',
	'http://www.elwatan.com/edito/rss.xml']
regex = [r'^https?:\/\/[^\/]*elwatan\.com']
videoregex = []
liveregex = []

wikidata = 'Q2529832'

